travis:
  secure:
    BINSTAR_TOKEN: HKHKSAaoi9ZyrRnqmk1vpwf7NZrHz/2Kd3AFh0U+mT7Wk0sCqYAiaF+n65RIkJc1jtwHwMtYhsLmNopqDbigFnO7iLii9u+HfcC5K6KtZ3HHBXWd6g+gdMFPPCR5E/BVHjJL54muOCOK6BeKz4wZWY+iTQy5SeM1k7q/lia1oXS+zap0xLMTyy3CNkrhC699ilqsn181nAn/jIdjwXQMNnuZtY5uUa3EHwMnzZFFzlhUzKReM4MlS2cNiKpp1KDv7XUUFi4shTQq4i28nh+MztsJWy0JwwmRT47gZ9wOluCML5C4dKbv7f7BJcVl6aWo7GTpM5t+1dD5fqsM1FO70Q6jGilu7gWreFrHOqtMUhnaevG2ZvCG2vlY/CdsWJe3auDqSVE8lYtLuTua2fS5VpA5NyehdUMGhUkuKeNpF1OV9zybs4daVJ7tfsVRTJDzqFvbZKQVtSIIXFZeScwilNatOuBBn1g0lmX+Cj+Lm/TXwKxKphf7qYBxVXr26JvVAP3PMUaJyQsCs3tlmBeGKQd/cigRPlGkB0vpYxsT2q3i+P3IhH9lOTA+1iMD6TQVPXtCPqDFhjSYFcJH/pW47qa1Zcq7JGSOIlGdxM+Y0JcVWfUfqcuv28nbq3tAbANsGnmDF5EMPYqzQ9ald/3geBo+qkrB6HNZ5b+2p8TFu5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
